# Generated by Django 4.2.7 on 2023-12-22 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0010_websitemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitemeta',
            options={'verbose_name_plural': 'Website Meta'},
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
